# null 값 치환 및 개수 확인

In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('/Users/linakim/Desktop/최종프로젝트/데이터_추출/기업개황.xlsx', converters={'corp_code':str})

In [ ]:
data.head(3)

In [5]:
# 불필요한 열 삭제 
newData = data.drop(['Unnamed: 0', 'status', 'message', 'stock_name', 'stock_code', 'ir_url'], axis=1)

In [ ]:
newData.head(3)

In [6]:
newData.isnull().sum()
# 초기의 null값은 이러하나, 실제 데이터에선 다양한 방식으로 데이터가 없음을 표현함. ('해당사항없음' 등.)

corp_code            0
corp_name            0
corp_name_eng     1436
ceo_nm              18
corp_cls             0
jurir_no          1756
bizr_no            836
adres                3
hm_url           47343
phn_no              16
fax_no           13669
induty_code        249
est_dt             311
acc_mt              79
dtype: int64

In [ ]:
# 널값이 제일 많은 행의 널이 아닌 값을 확인해봤으나 홈페이지가 대부분 작동하지 않음. -> 열 삭제 결정
newData.ir_url.loc[~data.ir_url.isnull()].iloc[4]

## null값 골라내기

In [5]:
import re

In [65]:
# null값 치환 : nan이 float 형이라 정규표현식을 적용시킬수 없으므로
newData = newData.fillna('999')
newData['corp_name_eng'].head(15)

0                                      Daco corporation
1                         ILSAN PHARMACEUTICAL CO.,LTD.
2                                    Good & LS Co.,Ltd.
3                                 HANLA PARKING CO.,LTD
4     Credipia 25th Asset Securitization Specialty L...
5                                              youn bao
6                           BROOKS-PRI Automation, Inc.
7             Maekyung International Business Incubator
8                                               CADBANK
9                        MYOP III Securitization L.L.C.
10                        MYOP II Securitization L.L.C.
11                         MYOP I Securitization L.L.C.
12                                    Possmedia.Co.,Ltd
13                              Yeun Hung Asia Co., Ltd
14                                                  999
Name: corp_name_eng, dtype: object

In [ ]:
# 999 갯수 확인

for column in newData3.columns:
    cnt = 0
    for value in newData3[column]:
        if(value == '999'):
            cnt += 1
    print(column, cnt)

## 함수

- 한글찾는 함수

In [7]:

def find_korean(data_list):
    result = []
    for data in data_list:
        result += re.compile('[|가-힣]+').findall(data)
    return result

 - 한글 값을 지우는 함수

In [8]:
def remove_korean(data_list):
    for i in range(len(data_list)):
        data_list.iloc[i] = re.sub('[|가-힣]+', '999', str(data_list.iloc[i]))

 - 한글이 들어있을시 전체 값을 '999'로

In [82]:
def remove_colval_kor(data_list):
    for i in range(len(data_list)):
       if (re.search('[|가-힣]+', str(data_list.iloc[i])) is not None):
          data_list.iloc[i] = '999'

- '-' 포함시 전체 값을 '999'로

In [100]:
def remove_colval_hypen(data_list):
    for i in range(len(data_list)):
       if (re.search('-', str(data_list.iloc[i])) is not None):
          data_list.iloc[i] = '999'

- '-' 지우는 함수

In [92]:
def remove_hypen(data_list):
    for i in range(len(data_list)):
        data_list.iloc[i] = re.sub('-', '', str(data_list.iloc[i]))

- 대문자를 소문자로 바꿔주는 함수

In [112]:
def upper_to_lower(data_list):
    for i in range(len(data_list)):
        data_list.iloc[i] = data_list.iloc[i].lower()

- 'http://www' 지우는 함수

In [116]:
def remove_http(data_list):
    for i in range(len(data_list)):
        data_list.iloc[i] = re.sub('http://', '', str(data_list.iloc[i]))
        data_list.iloc[i] = re.sub('www.', '', str(data_list.iloc[i]))

- '(' 지우는 함수

In [138]:
def remove_brace(data_list):
    for i in range(len(data_list)):
        data_list.iloc[i] = re.sub('[()]', '', str(data_list.iloc[i]))

- 공백 지우는 함수

In [126]:
def remove_space(data_list):
    for i in range(len(data_list)):
        data_list.iloc[i] = re.sub('[\s]', '', str(data_list.iloc[i]))

- '+' 지우는 함수

In [139]:
def remove_plus(data_list):
    for i in range(len(data_list)):
        data_list.iloc[i] = re.sub('[+]', '', str(data_list.iloc[i]))

### corp_name_eng

In [10]:
koreans = find_korean(newData['corp_name_eng'])
print(koreans)

['해당없음', '주', '해당없음', '주', '주', '극동', '없음', '주', '동우지앤씨', '없음', '주', '없음', '없음', '해당사항없음', '주', '없음', '해당사항', '없음', '해당사항', '없음', '없음', '없음', '한국전장주식회사', '김선경', '없슴', '수원시', '장안구', '조원동', '아일렛타운', '호', '주', '공신', '주', '주', '주', '없음', '주', '개발', '주', '주', '주', '주', '없음', '김종월', '없음', '없음', '주', '산업개발', '주', '없음', '주식회사', '남원사랑발전소', '주식회사', '서평', '파트너스', '없음', '없음', '주', '디자인벽지', '주식회사', '주', '에스모아제십일차', '주', '오에스디팟제이차', '주식회사', '주', '주', '대명메디칼프라자', '주', '없음', '주', '대전', '유성구', '봉명동', '디에이치파트너즈제사차', '주식회사', '없음', '개발', '개발', '주', '해당사항', '없슴', '주', '주', '주', '해당없음', '없음', '주', '주', '해당없음', '주', '주', '주', '약호', '푸른뫼', '비비토', '해당사항', '없슴', '해당없음', '주', '엠제이종합건설', '서성기', '해당사항없음', '주', '주', '주', '없음', '주', '없음', '없음', '없음', '해당사항', '없음', '없음', '주', '주', '주', '주', '종합건설', '해당없음', '주', '오피스텔', '없슴', '주', '주', '케이파이브제삼차', '주식회사', '주', '올레케이티제십칠차유동화전문', '유한회사', '주', '사랑누리', '주', '라운드시티', '주식회사', '주', '시장감시위원회', '퐁데보', '주식회사', '주', '호반리빙', '주', '주식회사대원빌딩', '뉴하노이', '주식회사', '조이오브스프링', '주식회사', '라운드스퀘어제일차', '주식회사', '라운드스퀘어제이차', '주식회사', '주식회사', '서을특별시', '영등포구', '국제금융로', '길', '여의도동', '장례타운', '없음', '주', '없음', '주', '도시개발', '누리주택건설', '주', '없음', '주', '큰희망', '주', '도온문화투자', '주식회사', '서울시', '마포구', '마포대로', '층', '공덕동', '주', '케이제이엠파트너즈제이차', '주식회사', '주', '주', '없음', '주식회사', '용진', '주식회사', '광명인베스트먼트', '케이씨지아이헬리오스제', '호사모투자', '합자회사', '주', '동광화섬주식회사', '창원', '주식회사', '개발', '주', '주', '주식회사제이알제', '호위탁관리부동산투자회사', '주', '주', '우창국제조사평가', '주', '종합개발', '주', '주', '부산광역시', '강서구', '화전산단', '로', '맑은김포주식회사', '주식회사마스턴제십일호위탁관리부동산투자회사', '주식회사', '세영유통', '없음', '주', '해당사항없음', '주', '주', '홀딩스', '주', '없음', '주', '주', '제', '호공공임대개발전문위탁관리부동산투자회사', '개발', '주', '주식회사', '없슴', '주', '케이비동자민간임대위탁관리부동산투자회사', '푸른순천환경주식회사', '푸른예산환경주식회사', '청정부산환경주식회사', '범섬리조트', '박종국', '주', '피엔디티', '없음', '없음', '주식회사바디프랜드', '리무진', '주', '종근당산업', '주', '주', '익산문화관리', '주', '주식회사', '주식회사', '그린워터텍', '주', '주', '주', '없음', '주', '개발', '주', '주', '케이와이리더스', '그린부산환경', '주', '협성건업', '주', '해당없음', '주', '여', '녀', '채', '주', '전익성', '센츄리', '주', '안동터미널', '없음', '층', '삼성동', '아셈타워', '주', '서울특별시', '마포구', '상암동', '누리꿈스퀘어연구개발타워', '층', '무']

In [67]:
newData2 = newData
type(newData2)

pandas.core.frame.DataFrame

In [68]:
# (주) 삭제 
for i in range(len(newData2['corp_name_eng'])):
    newData2['corp_name_eng'].iloc[i] = re.sub('[(주)]', '', newData2['corp_name_eng'].iloc[i])

In [69]:
newData2['corp_name_eng'].iloc[259]

'K.T.M'

In [13]:
# 삭제된것 확인 
koreans2 = find_korean(newData2['corp_name_eng'])
print(koreans2)

['해당없음', '해당없음', '극동', '없음', '동우지앤씨', '없음', '없음', '없음', '해당사항없음', '없음', '해당사항', '없음', '해당사항', '없음', '없음', '없음', '한국전장식회사', '김선경', '없슴', '수원시', '장안구', '조원동', '아일렛타운', '호', '공신', '없음', '개발', '없음', '김종월', '없음', '없음', '산업개발', '없음', '식회사', '남원사랑발전소', '식회사', '서평', '파트너스', '없음', '없음', '디자인벽지', '식회사', '에스모아제십일차', '오에스디팟제이차', '식회사', '대명메디칼프라자', '없음', '대전', '유성구', '봉명동', '디에이치파트너즈제사차', '식회사', '없음', '개발', '개발', '해당사항', '없슴', '해당없음', '없음', '해당없음', '약호', '푸른뫼', '비비토', '해당사항', '없슴', '해당없음', '엠제이종합건설', '서성기', '해당사항없음', '없음', '없음', '없음', '없음', '해당사항', '없음', '없음', '종합건설', '해당없음', '오피스텔', '없슴', '케이파이브제삼차', '식회사', '올레케이티제십칠차유동화전문', '유한회사', '사랑누리', '라운드시티', '식회사', '시장감시위원회', '퐁데보', '식회사', '호반리빙', '식회사대원빌딩', '뉴하노이', '식회사', '조이오브스프링', '식회사', '라운드스퀘어제일차', '식회사', '라운드스퀘어제이차', '식회사', '식회사', '서을특별시', '영등포구', '국제금융로', '길', '여의도동', '장례타운', '없음', '없음', '도시개발', '누리택건설', '없음', '큰희망', '도온문화투자', '식회사', '서울시', '마포구', '마포대로', '층공덕동', '케이제이엠파트너즈제이차', '식회사', '없음', '식회사', '용진', '식회사', '광명인베스트먼트', '케이씨지아이헬리오스제', '호사모투자', '합자회사', '동광화섬식회사', '창원', '식회사', '개발', '식회사제이알제', '호위탁관리부동산투자회사', '우창국제조사평가', '종합개발', '부산광역시', '강서구', '화전산단', '로', '맑은김포식회사', '식회사마스턴제십일호위탁관리부동산투자회사', '식회사', '세영유통', '없음', '해당사항없음', '홀딩스', '없음', '제', '호공공임대개발전문위탁관리부동산투자회사', '개발', '식회사', '없슴', '케이비동자민간임대위탁관리부동산투자회사', '푸른순천환경식회사', '푸른예산환경식회사', '청정부산환경식회사', '범섬리조트', '박종국', '피엔디티', '없음', '없음', '식회사바디프랜드', '리무진', '종근당산업', '익산문화관리', '식회사', '식회사', '그린워터텍', '없음', '개발', '케이와이리더스', '그린부산환경', '협성건업', '해당없음', '여', '녀', '채', '전익성', '센츄리', '안동터미널', '없음', '층', '삼성동', '아셈타워', '서울특별시', '마포구', '상암동', '누리꿈스퀘어연구개발타워', '층', '무']

In [70]:
newData3 = newData2

In [83]:
# 한글 영문명 칼럼 널처리
# for i in range(len(newData3['corp_name_eng'])):
#     newData3['corp_name_eng'].iloc[i] = re.sub('[|가-힣]+', '999', newData3['corp_name_eng'].iloc[i])

remove_colval_kor(newData3['corp_name_eng'])

In [84]:
# 삭제된것 확인 
koreans3 = find_korean(newData3['corp_name_eng'])
print(koreans3)

[]

In [ ]:
# 999로 치환된것의 개수는 1515, 즉 널값이 1515개 
sum = 0
for i in range(len(newData3['corp_name_eng'])):
    if (newData3['corp_name_eng'].iloc[i] == '999'):
        sum += 1
        
print(sum)

In [85]:
len(newData3['corp_name_eng'])

80939

### jurir_no

In [ ]:
# jurir_no 칼럼에 '추후기재'라는 값의 인덱스 확인 
for i in range(len(newData3['jurir_no'])):
    if(len(newData3['jurir_no'].iloc[i]) < 13 and newData3['jurir_no'].iloc[i] != '999'):
        print(i)
#         print()
#         print(no)

In [86]:
newData3['jurir_no'].iloc[20719] = '999'

In [20]:
newData3['jurir_no'].iloc[20719]

'999'

### bizr_no

- 한글이 포함된 값 지우기

In [87]:
korean_in_bizr_no = find_korean(newData3['bizr_no'])

In [88]:
print(korean_in_bizr_no)

['외투', '외투', '호', '외투', '등록번호', '제', '호', '제', '호', '제', '호', '외투', '호', '외투', '해당없음', '해당없음', '외투', '해당없음', '기업외투제', '호', '추후기재', '외투', '호', '신고', '외투', '외투', '제', '호', '외투', '외투']

In [89]:
remove_colval_kor(newData3['bizr_no'])

In [90]:
newData3['bizr_no'].iloc[217]

'999'

In [91]:
# 깔끔하게 다 지워진것 확인
korean_in_bizr_no2 = find_korean(newData3['bizr_no'])
print(korean_in_bizr_no2)

[]

- '-' 없애기

In [95]:
remove_hypen(newData3['bizr_no'])

In [96]:
print(newData3['bizr_no'].iloc[4])

1078608501

- 영어 포함값 없애기

### hm_url

- 한글 없애기

In [97]:
find_korean(newData3['hm_url'])

['없음',
 '해당사항없음',
 '해당없음',
 '해당없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '없음',
 '해당없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '해당없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '무',
 '상임대리인',
 '한빛은행',
 '없음',
 '없음',
 '없음',
 '해당없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없슴',
 '해당사항없음',
 '없슴',
 '해당없음',
 '해당없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '해당사항없음',
 '해당사항',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '무',
 '해당없슴',
 '없음',
 '처리중',
 '없음',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '준비중',
 '해당',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당없음',
 '없음',
 '해당없음',
 '없음',
 '해당없음',
 '해당사항',
 '없음',
 '해당사항',
 '없슴',
 '없음',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '해당사항없음',
 '없음',
 '해당사항없슴',
 '무',
 '없슴',
 '없음',
 '없슴',
 '무',
 '무',
 '없음',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '해당사항',
 '없음',
 '없음',
 '해당사항',
 '무',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '무',
 '해당사항없음',
 '없음',
 '무',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없슴',
 '해당사항없슴',
 '해당없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '해당사항없슴',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '해당사항없음',
 '해당사항',
 '없음',
 '없음',
 '해당무',
 '없음',
 '해당사항없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '해당없슴',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '해당없음',
 '없음',
 '해당사항',
 '없음',
 '해당사항',
 '없음',
 '무',
 '해당사항없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없슴',
 '없음',
 '무',
 '없음',
 '없음',
 '해당없음',
 '없음',
 '작성중',
 '상임대리인',
 '한빛은행',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '한국전장주식회사',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당없음',
 '없슴',
 '해당없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '해당사항',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '해당사항',
 '없음',
 '없슴',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '무',
 '없음',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '없음',
 '없음',
 '해당사항없슴',
 '없음',
 '해당없음',
 '무',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '해당사항없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없슴',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '자산건설',
 '없음',
 '없슴',
 '없음',
 '구룡촌',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '해당사항',
 '없음',
 '없슴',
 '해당없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '새싹땅콩',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '없슴',
 '없음',
 '원목마루',
 '무',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '분철',
 '없음',
 '없음',
 '없음',
 '없슴',
 '무',
 '무',
 '없슴',
 '원광',
 '업음',
 '겨레석재',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '없음',
 '무',
 '없음',
 '없음',
 '폐수수탁처리',
 '해당사항없음',
 '없음',
 '없음',
 '동광합철',
 '한국',
 '무',
 '없음',
 '서대전컨벤션',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '무',
 '없슴',
 '무',
 '없음',
 '없음',
 '태양개발',
 '해정',
 '없음',
 '안산',
 '없음',
 '무',
 '없음',
 '강구조',
 '없음',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '없음',
 '동진하이테크',
 '한국',
 '없음',
 '무',
 '없음',
 '없음',
 '무',
 '현대기계',
 '해당사항없음',
 '현재',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없음',
 '개설중',
 '해당없음',
 '해당없음',
 '해당없음',
 '해당사항',
 '없음',
 '준비중',
 '없음',
 '해당사항',
 '없슴',
 '없슴',
 '없음',
 '해당사항',
 '없음',
 '작업중',
 '없음',
 '없음',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '무',
 '무',
 '없음',
 '무',
 '없음',
 '해당무',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '없슴',
 '없슴',
 '해당없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '해당사항',
 '없음',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없슴',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '해당없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없슴',
 '해당사항없슴',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '해당없음',
 '두원정밀',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '해당사항없음',
 '해당없음',
 '없슴',
 '없음',
 '없음',
 '해당없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '해당없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '무',
 '없음',
 '없음',
 '해당사항없음',
 '해당없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '해당없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없슴',
 '없슴',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없슴',
 '서울시',
 '관악구',
 '봉천',
 '동',
 '없음',
 '좋은집디앤씨',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '없슴',
 '해당사항없음',
 '없음',
 '없슴',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없슴',
 '없음',
 '해당사항없음',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없슴',
 '해당없음',
 '해당없음',
 '해당없음',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '무',
 '해당없음',
 '없음',
 '한샘글로피아',
 '없음',
 '해당',
 '없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '해당없음',
 '안성버섯랜드',
 '없음',
 '윙바디',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없슴',
 '에스엔에스',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '한림종합건설',
 '없음',
 '하나린라이프',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '인쇄회로기판제조',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '아르누보팰리스',
 '없음',
 '포레스힐',
 '없음',
 '없음',
 '내뜰애',
 '없음',
 '없음',
 '대상단조',
 '없음',
 '대구웨딩',
 '없슴',
 '조립',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '콘크리트파일',
 '한국',
 '해당없음',
 '무',
 '없음',
 '없음',
 '없음',
 '조명제조',
 '무',
 '데코시트지',
 '없음',
 '없슴',
 '없음',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '없음',
 '해당사항',
 '없음',
 '무',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '없슴',
 '없음',
 '무',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '현대',
 '지구영농조합',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '삼라희망재단',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '없음',
 '크레인무역',
 '없음',
 '없음',
 '없음',
 '없음',
 '월드여행사',
 '없음',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '국화장례문화원',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '무',
 '해당무',
 '없음',
 '없음',
 '해당사항없음',
 '해당사항없음',
 '없음',
 '에이제이테크',
 '없음',
 '라메종',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '흥덕건설',
 '없음',
 '해당없음',
 '없음',
 '없음',
 '무',
 '해당없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '무',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당없음',
 '없음',
 '해당사항없음',
 '없슴',
 '없음',
 '해당없음',
 '무',
 '없음',
 '없음',
 '울릉심층수',
 '없음',
 '에어댐퍼',
 '없음',
 '바나나여행',
 '여의도투자자문',
 '없음',
 '없음',
 '해운대온천센터',
 '없음',
 '동광어시장',
 '없음',
 '없음',
 '라움빌리지',
 '제이비',
 '물티슈제조',
 '무',
 '파주산단',
 '없음',
 '도경',
 '없음',
 '무',
 '없음',
 '주광',
 '없음',
 '없슴',
 '무',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당없음',
 '남문',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '비료',
 '해당사항없음',
 '없음',
 '에코텍',
 '명진닷컴',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '없음',
 '없음',
 '해당없슴',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당무',
 '없음',
 '없음',
 '없음',
 '성문회계법인',
 '없음',
 '일단',
 '이번주',
 '금요일날',
 '밥',
 '먹고',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '백플레이트',
 '없음',
 '없슴',
 '없음',
 '해당사항없음',
 '없슴',
 '없음',
 '해당사항없음',
 '삼성파워텍',
 '없음',
 '없음',
 '창원동전산단',
 '해당없음',
 '없음',
 '없슴',
 '없음',
 '없음',
 '없음',
 '없음',
 '니케',
 '없슴',
 '가장맛있는족발',
 '미래생활',
 '없음',
 '없음',
 '대승주택',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '해당사항없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '없음',
 '방부목공장',
 '없음',
 '없음',
 '없슴',
 '없음',
 '광득사랑',
 '전보산업',
 '없음',
 '해당사항없음',
 '해당사항없슴',
 '없음',
 '없음',
 '없음',
 '해당사항',
 '없음',
 '없음',
 '없음',
 '이산화탄소',
 '없음',
 '해당없음',
 '없음',
 '없음',
 '대구농산',
 '없음',
 ...]

In [98]:
remove_colval_kor(newData3['hm_url'])

In [ ]:
find_korean(newData3['hm_url'])

- '-' 값 없애기

In [101]:
remove_colval_hypen(newData3['hm_url'])

In [106]:
newData3['hm_url'].iloc[27]

'999'

- 앞에 http://, www 지우기

In [117]:
remove_http(newData3['hm_url'])

In [113]:
upper_to_lower(newData3['hm_url'])

In [109]:
newData3['hm_url'].iloc[8]

'cadbank.co.kr'

In [118]:
newData3['hm_url'].iloc[130]

'youngfuture.com'

### phn_no

- '-' 빼기

In [119]:
remove_hypen(newData3['phn_no'])

- '(' 빼기

In [133]:
remove_brace(newData3['phn_no'])

- 공백제거

In [127]:
remove_space(newData3['phn_no'])

In [135]:
newData3['phn_no'].iloc[86]

'027999114'

- 한글 없애기

In [130]:
remove_colval_kor(newData3['phn_no'])

In [ ]:
newData3['phn_no'].iloc[75613] = '0226278100'

- '+' 없애기

In [141]:
remove_plus(newData3['phn_no'])

In [142]:
newData3['phn_no'].iloc[124]

'81352187000'

- 국가코드 열 추가

In [143]:
# 초기값 82 
newData3['country_code'] = '82'

In [145]:
newData3['phn_no'].iloc[34218] = newData3['phn_no'].iloc[34218][1:]

In [146]:
newData3['phn_no'].iloc[34218]

'15166775'

In [149]:
newData3['phn_no'].iloc[2427]

'4904038617650'

In [ ]:
codes = ['1', '44', '81', '852', '86', '60', '01', '49', '33', '352', '31', '61', '47', '65', '213', '41']]

In [168]:
codesThr = ['852', '352', '213']

In [169]:
codesTwo = ['44', '81','86', '60', '49', '33','31', '61', '47', '65','41']

In [170]:
codesOne = ['1']

In [166]:
# phn_no의 첫 세자리만 떼서 새로운 열에 저장 
newData3['phn_no_first_three'] = '999'
for i in range(len(newData3['phn_no_copy'])):
    newData3['phn_no_first_three'].iloc[i] = newData3['phn_no_copy'].iloc[i][:3]

In [315]:
newData3.drop(['phn_no_first_three'], axis=1, inplace=True)

In [159]:
newData3['phn_no_copy'] = newData3['phn_no']

In [160]:
# country_code 칼럼에 넣기 전 데이터 복사
newData3['phn_no_copy'].head(5)

0    0415651800
1    0337637535
2    0262638185
3    0647968001
4     077687911
Name: phn_no_copy, dtype: object

In [316]:
newData3.drop(['phn_no_copy'], axis=1, inplace=True)

In [313]:
newData3['phn_no'].head(5)

0    0415651800
1    0337637535
2    0262638185
3    0647968001
4     077687911
Name: phn_no, dtype: object

In [167]:
newData3['phn_no_first_three'].head(5)

0    041
1    033
2    026
3    064
4    077
Name: phn_no_first_three, dtype: object

In [171]:
# 국가 전화번호 코드가 세자리인것을 먼저 추출. 
for i in range(len(newData3['phn_no_first_three'])):
    if newData3['phn_no_first_three'].iloc[i] not in codesThr:
        newData3['phn_no_first_three'].iloc[i] = newData3['phn_no_first_three'].iloc[i][:2]
    else :
        newData3['country_code'].iloc[i] = newData3['phn_no_first_three'].iloc[i]

In [174]:
newData3['country_code'].iloc[80618]

'852'

In [175]:
# 국가 전화번호 코드가 두자리인것 추출 
for i in range(len(newData3['phn_no_first_three'])):
    if newData3['phn_no_first_three'].iloc[i] not in codesTwo:
        newData3['phn_no_first_three'].iloc[i] = newData3['phn_no_first_three'].iloc[i][:1]
    else :
        newData3['country_code'].iloc[i] = newData3['phn_no_first_three'].iloc[i]

In [176]:
newData3['country_code'].iloc[124]

'81'

In [177]:
# 국가 전화번호 코드가 한자리인것 추출 
for i in range(len(newData3['phn_no_first_three'])):
    if newData3['phn_no_first_three'].iloc[i] not in codesOne:
        newData3['phn_no_first_three'].iloc[i] = '999'
    else :
        newData3['country_code'].iloc[i] = newData3['phn_no_first_three'].iloc[i]

In [178]:
newData3['country_code'].iloc[6379]

'1'

In [182]:
newData3['country_code'].head(5)

0    82
1    82
2    82
3    82
4    82
Name: country_code, dtype: object

In [ ]:
# 더이상 필요 없는 열 삭제
newData3.drop(['phn_no_first_three'], ['phn_no_copy'], axis=1, inplace=True)

### fax_no

In [183]:
# '-' 빼기
remove_hypen(newData3['fax_no'])
# '(' 빼기 
remove_brace(newData3['fax_no'])
# 공백제거
remove_space(newData3['fax_no'])
# 한글 없애기
remove_colval_kor(newData3['fax_no'])
# '+' 없애기
remove_plus(newData3['fax_no'])

In [184]:
# 새 국가코드 열 추가
newData3['fax_no_copy'] = newData3['fax_no']

In [312]:
newData3['fax_no_copy'].head(5)

KeyError: 'fax_no_copy'

In [ ]:
newData3['fax_no_first_three'].head(5)

In [187]:
# fax_no의 첫 세자리만 떼서 새로운 열에 저장 
newData3['fax_no_first_three'] = '999'
for i in range(len(newData3['fax_no_copy'])):
    newData3['fax_no_first_three'].iloc[i] = newData3['fax_no_copy'].iloc[i][:3]

In [190]:
# 초기값 82 
newData3['country_code_fax'] = '82'

In [ ]:
newData3['fax_no'].head(5)

In [188]:
newData3['fax_no_first_three'].head(5)

0    041
1    033
2    999
3    064
4    784
Name: fax_no_first_three, dtype: object

In [191]:
# 국가 전화번호 코드가 세자리인것을 먼저 추출. 
for i in range(len(newData3['fax_no_first_three'])):
    if newData3['fax_no_first_three'].iloc[i] not in codesThr:
        newData3['fax_no_first_three'].iloc[i] = newData3['fax_no_first_three'].iloc[i][:2]
    else :
        newData3['country_code_fax'].iloc[i] = newData3['fax_no_first_three'].iloc[i]

In [192]:
# 국가 전화번호 코드가 두자리인것 추출 
for i in range(len(newData3['fax_no_first_three'])):
    if newData3['fax_no_first_three'].iloc[i] not in codesTwo:
        newData3['fax_no_first_three'].iloc[i] = newData3['fax_no_first_three'].iloc[i][:1]
    else :
        newData3['country_code_fax'].iloc[i] = newData3['fax_no_first_three'].iloc[i]

In [193]:
# 국가 전화번호 코드가 한자리인것 추출 
for i in range(len(newData3['fax_no_first_three'])):
    if newData3['fax_no_first_three'].iloc[i] not in codesOne:
        newData3['fax_no_first_three'].iloc[i] = '999'
    else :
        newData3['country_code_fax'].iloc[i] = newData3['fax_no_first_three'].iloc[i]

In [197]:
newData3['country_code_fax'].head(50)

0     82
1     82
2     82
3     82
4     82
5     82
6     82
7     82
8     82
9     82
10    82
11    82
12    82
13    82
14    82
15    82
16    82
17    82
18    82
19    82
20    82
21    82
22    82
23    82
24    82
25    82
26    82
27    82
28    82
29    82
30    82
31    82
32    82
33    82
34    82
35    82
36    82
37    82
38    82
39    82
40    82
41    82
42    82
43    82
44    82
45    82
46    82
47    82
48    65
49    82
Name: country_code_fax, dtype: object

In [199]:
# 더이상 필요 없는 열 삭제
newData3.drop(['fax_no_first_three'], axis=1, inplace=True)

In [200]:
newData3.drop(['fax_no_copy'], axis=1, inplace=True)

In [202]:
newData4 = newData3.replace('999', 'NaN')

In [205]:
newData4.to_csv('기업개황_v2(3).csv', encoding='euc-kr', index=False)

### ceo_nm

- 대표 이름을 담을 dataframe 생성

In [206]:
ceo_data = {'corp_code' : newData4['corp_code'],
           'ceo_nm' : newData4['ceo_nm']}

In [211]:
from pandas import Series, DataFrame

In [216]:
ceo_df = DataFrame(ceo_data)

In [217]:
ceo_df.head(10)

  corp_code              ceo_nm
0  00434003                 김상규
1  00434456                 이광선
2  00430964                 정진형
3  00432403                 정우석
4  00388953                 배경오
5  00179984                 이연우
6  00420143  Robert J. Therrien
7  00401111                 김정실
8  00435534                 임장순
9  00430186                 김지홍

- 한글로 된 이름중 공백 지우기

In [218]:
for i in range(len(ceo_df['ceo_nm'])):
       if (re.search('[|가-힣]+', str(ceo_df['ceo_nm'].iloc[i])) is not None):
          ceo_df['ceo_nm'].iloc[i] = re.sub('[\s]', '', str(ceo_df['ceo_nm'].iloc[i]))

In [221]:
ceo_df.head(5)

  corp_code ceo_nm
0  00434003    김상규
1  00434456    이광선
2  00430964    정진형
3  00432403    정우석
4  00388953    배경오

- 두명 이상인경우 행을 하나 더 만들기

In [224]:
# 코딩을 위해 깊은복사로 df 하나 더 만들어놓기 
ceo_df2 = ceo_df.copy(deep=True)

In [225]:
ceo_df2.head(5)

  corp_code ceo_nm
0  00434003    김상규
1  00434456    이광선
2  00430964    정진형
3  00432403    정우석
4  00388953    배경오

In [302]:
# 반복문을 돌며 복수개의 대표 이름을 각각의 행으로 담을 새로운 df 생성
new_ceo_df = pd.DataFrame(columns=['corp_code', 'ceo_nm'])

In [288]:
len(new_ceo_df)

0

In [303]:
# 대표명에 쉼표가 들어갔을시 쉼표로 split한 리스트를 새로운 df에 저장
cnt = 0
for i in range(len(ceo_df2)):
    if(re.search('[|가-힣]+', str(ceo_df2['ceo_nm'].iloc[i])) is not None):
        if("," in ceo_df2['ceo_nm'].iloc[i] ):
            names = ceo_df2['ceo_nm'].iloc[i].split(',')
            for j in range(len(names)):
                new_ceo_df.loc[cnt] = [ceo_df2['corp_code'].iloc[i], names[j]]
                cnt = cnt + 1
        elif "." in ceo_df2['ceo_nm'].iloc[i]:
            names = ceo_df2['ceo_nm'].iloc[i].split('.')
            for j in range(len(names)):
                new_ceo_df.loc[cnt] = [ceo_df2['corp_code'].iloc[i], names[j]]
                cnt = cnt + 1
        else:
            new_ceo_df.loc[cnt] = [ceo_df2['corp_code'].iloc[i], ceo_df2['ceo_nm'].iloc[i]]
    else:
        new_ceo_df.loc[cnt] = [ceo_df2['corp_code'].iloc[i], ceo_df2['ceo_nm'].iloc[i]]
    cnt = cnt + 1

In [300]:
new_ceo_df['ceo_nm'].iloc[1395]

'강제호'

In [286]:
new_ceo_df.to_csv('대표자_v1.csv', encoding='euc-kr')

In [304]:
len(new_ceo_df)

84799

In [305]:
new_ceo_df.to_csv('대표자_v3.csv', encoding='euc-kr')

## 마무리하고 대표자 칼럼 지우고 저장

In [306]:
newData3.drop(['ceo_nm'], axis=1, inplace=True)

In [310]:
newData3.to_csv('기업개황_v3.csv', encoding='euc-kr', converters={'corp_code': lambda x: str(x)})

In [311]:
newData3['corp_code'].head(4)

0    00434003
1    00434456
2    00430964
3    00432403
Name: corp_code, dtype: object

In [319]:
# 칼럼 순서바꾸기 
newData4 = newData3[['corp_code', 'corp_name', 'corp_name_eng', 'jurir_no', 'bizr_no', 'adres', 'hm_url', 'country_code', 'phn_no', 'country_code_fax', 'fax_no', 'induty_code', 'est_dt', 'acc_mt']]

In [320]:
newData4.head()

,corp_code,corp_name,corp_name_eng,jurir_no,bizr_no,adres,hm_url,country_code,phn_no,country_code_fax,fax_no,induty_code,est_dt,acc_mt
0,00434003,(주)다코,Daco corporation,1615110021778,3128134722,충청남도 천안시 청당동 419-12,999,82,0415651800,82,0415636808,25931,1.99706e+07,12
1,00434456,일산약품(주),"ILSAN PHARMACEUTICAL CO.,LTD.",1412110004641,2248105027,강원도 원주시 원동 303,999,82,0337637535,82,0337636433,21101,1.99106e+07,12
2,00430964,굿앤엘에스주식회사,"Good & LS Co.,Ltd.",1101112672875,1048177488,서울특별시 중구 태평로2가 120,999,82,0262638185,82,999,64999,2.00212e+07,11
3,00432403,한라판지(주),"HANLA PARKING CO.,LTD",2201110019993,6168120149,제주특별자치도 북제주군 한림읍 상명리 587,999,82,0647968001,82,0647968003,17123,1.99706e+07,12
4,00388953,크레디피아제이십오차유동화전문회사,Credipia 25th Asset Securitization Specialty L...,1101140036118,1078608501,서울특별시 영등포구 여의도동 36-3,999,82,077687911,82,7849869,64999,2.00111e+07,10

In [327]:
newData4 = newData4.replace('999', 'NaN')

In [328]:
newData4.to_excel('기업개황_v3.xlsx', encoding='euc-kr')

In [330]:
new_ceo_df.to_excel('대표자_v4.xlsx', encoding='euc-kr')